"""empty message

Revision ID: a91c1ca890e9
Revises: 7c1d644b5e06
Create Date: 2021-07-09 12:13:38.059018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91c1ca890e9'
down_revision = '7c1d644b5e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('income', sa.Numeric(asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'income')
    # ### end Alembic commands ###
