"""empty message

Revision ID: 81c4ae806acc
Revises: 
Create Date: 2021-07-05 19:00:20.954666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c4ae806acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=40), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_description', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('amount_owed', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('interest_rate', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('interest_rate', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('limit', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reoccurings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_description', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_description', sa.String(length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_obligations')
    op.drop_table('monthly_reoccurings')
    op.drop_table('credit_cards')
    op.drop_table('assets')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
