"""empty message

Revision ID: e1f05aeab41a
Revises: 55e9ef93f31f
Create Date: 2021-07-01 04:30:32.138965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f05aeab41a'
down_revision = '55e9ef93f31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=40), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_description', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Numeric(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(), nullable=True),
    sa.Column('limit', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_description', sa.String(length=50), nullable=False),
    sa.Column('current_balance', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_obligations')
    op.drop_table('credit_cards')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
